### ISSUE TITLE
ueditor是不是不支持angular ui-router?

### ISSUE THREAD

**Issue by maozhenhua2** [fex-team/ueditor#1989]
.config(function ($stateProvider, $urlRouterProvider) {
    $stateProvider.
      state('list', {
        url: '/',
        templateUrl: 'NewsList',
        controller: 'ListController'
      }).
      state('h5', {
        url: '/h5',
        templateUrl: 'H5NewsDetail',
        controller: 'H5Controller'
      }).
      state('text', {
        url: '/text',
        templateUrl: 'TextNewsDetail',
        controller: 'TextController'
      })
  })

用了https://github.com/zqjimlove/angular-ueditor这个

我在TextNewsDetail这个页面里放了ueditor，第一次加载的时候是好的，但是只要进入别的页面然后在回到这个页面就会出错

TypeError: Cannot read property 'length' of undefined
    at null.<anonymous> (http://localhost:3174/Scripts/angular/angular-ueditor.js:59:41)
    at h.ready (http://localhost:3174/Scripts/UEEditor1_4_3/ueditor.all.min.js:94:455)
    at _NGUeditor.initEditor (http://localhost:3174/Scripts/angular/angular-ueditor.js:48:36)
    at new _NGUeditor (http://localhost:3174/Scripts/angular/angular-ueditor.js:27:22)
    at link (http://localhost:3174/Scripts/angular/angular-ueditor.js:90:13)
    at http://localhost:3174/Scripts/angular/angular.min.js:70:141
    at $ (http://localhost:3174/Scripts/angular/angular.min.js:70:197)
    at B (http://localhost:3174/Scripts/angular/angular.min.js:59:255)
    at g (http://localhost:3174/Scripts/angular/angular.min.js:51:335)
    at B (http://localhost:3174/Scripts/angular/angular.min.js:59:199) <div class="ueditor ng-pristine ng-untouched ng-valid ng-isolate-scope" id="NewsContent" name="NewsContent" config="config" ng-model="g.editData.NewsContent">
angular.min.js:102 TypeError: Cannot set property 'innerHTML' of null
    at a (ueditor.all.min.js:676)
    at null.<anonymous> (ueditor.all.min.js:681)
    at Z.fireEvent (ueditor.all.min.js:21)
    at null.<anonymous> (ueditor.all.min.js:249)
    at Z.fireEvent (ueditor.all.min.js:21)
    at h.setContent (ueditor.all.min.js:109)
    at _NGUeditor.setEditorContent (angular-ueditor.js:73)
    at _NGUeditor.bindRender.ctrl.$render (angular-ueditor.js:83)
    at Object.<anonymous> (angular.min.js:228)

不知道是什么问题

**Comment by zhang421755327** [comment]
同上，怎么没人有解决方案啊

**Comment by zhang421755327** [comment]
你在调用的directive要调用ueditor本身的方法手动destory，要不你是看不到的
、var instance;
                    if (typeof UM !== 'undefined') {
                        instance = UM.getEditor('editor', {
                            toolbar: [
                                'source | undo redo | bold italic underline strikethrough | superscript subscript | forecolor backcolor | removeformat |',
                                'insertorderedlist insertunorderedlist | selectall cleardoc image paragraph | fontfamily fontsize',
                                '| justifyleft justifycenter justifyright justifyjustify',
                                '| link unlink'
                            ]
                        });
                    }

                    $scope.$on('$destroy', function() {
                        instance.destroy();
                    });
