### ISSUE TITLE
jsp版本图片上传错误

### ISSUE THREAD

**Issue by tvrcfdfe** [fex-team/ueditor#1992]
我用的是最新版本1.4.3 jsp版本的 因为和struts2结合了 刚开始报错是未找到上传数据，百度了一下 说是要添加一个过滤器，就按照要求添加了，可是现在报上传失败。
 是不是还有其他配置 比如上传路径之类的。我现在只添加了一个自定义过滤器 就报错：
第一行是url地址 第二行是方法进入到自定义过滤器，最后一行是我的过滤器方法
/InformationBulletin/ueditor/jsp/controller.jsp
使用自定义过滤
五月 04, 2015 11:38:03 上午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet jsp threw exception
java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.getTempDirectory()Ljava/io/File;
	at com.baidu.ueditor.upload.StorageManager.getTmpFile(StorageManager.java:117)
	at com.baidu.ueditor.upload.StorageManager.saveFileByInputStream(StorageManager.java:51)
	at com.baidu.ueditor.upload.BinaryUploader.save(BinaryUploader.java:75)
	at com.baidu.ueditor.upload.Uploader.doExec(Uploader.java:24)
	at com.baidu.ueditor.ActionEnter.invoke(ActionEnter.java:80)
	at com.baidu.ueditor.ActionEnter.exec(ActionEnter.java:49)
	at org.apache.jsp.ueditor.jsp.controller_jsp._jspService(controller_jsp.java:61)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:393)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:320)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:266)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.weiz.filter.MyStruts2Filter.doFilter(MyStruts2Filter.java:36)

**Comment by tvrcfdfe** [comment]
下面是我的过滤器，执行到使用自定义过滤器的下一句就报错
public void doFilter(ServletRequest req, ServletResponse res,FilterChain chain) throws IOException, ServletException {
        HttpServletRequest request = (HttpServletRequest) req;
        //不过滤的url
        String url = request.getRequestURI();
        String contextPath=request.getContextPath(); 
        HttpServletResponse response = (HttpServletResponse) res;    
        System.out.println(url);
        if (url.endsWith("controller.jsp")) {
            System.out.println("使用自定义的过滤器");           
            chain.doFilter(req, res);
        }else{
            System.out.println("使用默认的过滤器");
            super.doFilter(req, res, chain);
        }
    }
}

**Comment by tvrcfdfe** [comment]
刚解决一点点 发现是jar的问题 myeclipse 添加的struts2自动添加了一个io的低版本 现在在服务器上删除了  可以上传成功了  路径是webapps\InformationBulletin\ueditor\jsp\upload\image
但是 显示的时候 页面只显示图片名片 怎么解决
