### ISSUE TITLE
ueditor跨域请求解决方案的讨论

### ISSUE THREAD

**Issue by Jinqn** [fex-team/ueditor#205]
针对使用ueditor向跨域的后台发请求,这里提出一些解决的方法,有建议和更好的解决方案,可以在这里一起讨论:
http://fex.baidu.com/ueditor/#dev-crossdomain

**Comment by chengtianshuang** [comment]
有没有java关于ueditor跨域上传的例子啊？可以发我一份吗？1079831558@qq.com

**Comment by chengtianshuang** [comment]
有没有java关于ueditor跨域上传的例子啊？可以发我一份吗？1079831558@qq.com

**Comment by chengtianshuang** [comment]
有没有java关于ueditor跨域上传的例子啊？可以发我一份吗？1079831558@qq.com

**Comment by reyhappen** [comment]
@chengtianshuang 没有

**Comment by chengtianshuang** [comment]
（jsp）使用ueditor跨域上传附件，fireBug:
Error: Permission denied to access property '$EDITORUI'
dialog = parent.$EDITORUI[window.frameElement.id.replace( /_iframe$/, '' )];
internal.js (第 5 行，第 4 列)

ReferenceError: $G is not defined
var tabs = $G('tabhead').children;
attachment.js (第 20 行，第 12 列)

这种情况下怎么处理？

**Comment by kemingcao** [comment]
（jsp）使用ueditor跨域上传附件，fireBug:
Error: Permission denied to access property '$EDITORUI'
dialog = parent.$EDITORUI[window.frameElement.id.replace( /_iframe$/, '' )];
internal.js (第 5 行，第 4 列)

ReferenceError: $G is not defined
var tabs = $G('tabhead').children;
attachment.js (第 20 行，第 12 列)

这种情况下怎么处理？

**Comment by wangld2015** [comment]
有事试过通过上传图片回调的事件解决。

**Comment by 449684471** [comment]
@ypa9633 赞同这个方法，因为没有更好的方法。

**Comment by wangld2015** [comment]
我没有试这个方法，不知道可以吗，等试试

**Comment by wangld2015** [comment]
通过图片上传事件不可以，

**Comment by wangld2015** [comment]
能来个人给个提示吗？

**Comment by jluwoniu** [comment]
@tomener 我也出现这个问题了,请问你的问题解决了吗?

**Comment by wangld2015** [comment]
什么问题，多图解决了，单图没有解决






在2015年12月17 14时37分, "jluwoniu"<notifications@github.com>写道:



@tomener 我也出现这个问题了,请问你的问题解决了吗?

**Comment by 553859011** [comment]
这是我本地的配置：
UEditor 的页面在http://my.ueditor.xiaoma下，serverUrl指向域名在 http://test.ueditor.xiaoma域下
上传单图片时  服务器已经成功将图片保存了，但是页面处理时，出现错误，

Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://my.ueditor.xiaoma" from accessing a cross-origin frame.
    at Error (native)
    at HTMLIFrameElement.eval (eval at evaluate (unknown source), <anonymous>:1:7)
    at Object.InjectedScript._evaluateOn (<anonymous>:875:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:808:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:933:21)
    at HTMLIFrameElement.callback (http://test.ueditor.xiaoma/ueditor.all.js:24465:25)

**Comment by zhangheng4117** [comment]
单张图片的有兼容问题，后来我把上传单张图片的按钮去掉了。



张恒
 
发件人： 553859011
发送时间： 2015-12-29 16:46
收件人： fex-team/ueditor
抄送： zhangheng
主题： Re: [ueditor] ueditor跨域请求解决方案的讨论 (#205)
这是我本地的配置：
UEditor 的页面在http://my.ueditor.xiaoma下，serverUrl指向域名在 http://test.ueditor.xiaoma域下
上传单图片时 服务器已经成功将图片保存了，但是页面处理时，出现错误，
Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://my.ueditor.xiaoma" from accessing a cross-origin frame.
at Error (native)
at HTMLIFrameElement.eval (eval at evaluate (unknown source), :1:7)
at Object.InjectedScript._evaluateOn (:875:55)
at Object.InjectedScript._evaluateAndWrap (:808:34)
at Object.InjectedScript.evaluateOnCallFrame (:933:21)
at HTMLIFrameElement.callback (http://test.ueditor.xiaoma/ueditor.all.js:24465:25)

**Comment by 553859011** [comment]
@zhangheng4117   我感觉不像是兼容问题啊    倒像是跨域的问题

**Comment by zhangheng4117** [comment]
单张图片上传，提交按钮上传后target到了一个iframe里面，这个跨域的话读取不到里面的内容。
但是如果再跳转到本站的一个页面的话就可以获取的到，但是这个跳转页面的时候有兼容性问题。



张恒
 
发件人： 553859011
发送时间： 2015-12-30 00:03
收件人： fex-team/ueditor
抄送： zhangheng
主题： Re: [ueditor] ueditor跨域请求解决方案的讨论 (#205)
@zhangheng4117 我感觉不像是兼容问题啊 倒像是跨域的问题

**Comment by liuxiang** [comment]
先整理下场景: 
服务器 a.com
前端页 b.com

UEdit(b.com) -iframe请求->服务器(a.com)
-----------------------------------------------------------------
拆解:
UEdit(b.com) -iframe              跨域.使用domain解决
iframe请求->服务器(a.com)   不跨域

单图上传,使用内嵌iframe方式,而内嵌的iframe请求服务端,是以独立客户端访问,而此方式是不存在跨域的(也是解决跨域问题的常用手段),后台接口虽不存了跨域问题,那么为什么还出错呢?
原因是父页面与内嵌的iframe页面跨域了. 
解决办法:父页面与iframe设置同样的domain.

理论上问题解决了,方案简单,多见,大家也使用了此方式,并没有解决.原因为何,就不知道了(UEdit为提供iframe的domain设置入口,还是源码并不好修改...)
------------------------------------------------------------------------------
想到一个还未经验证的思路...
跨域本质是浏览器的保护机制,解决跨域的办法一条大主线就是如何让应用不跨域(满足`同源规则`,iframe也是一种示例,只不过又带来了新的跨域问题)

我的想法是:
UEdit(b.com)-iframe请求->转发器(b.com)->服务器(a.com)[同意跨域] 

拆解:
UEdit(b.com)-iframe                   因改变了iframe目标为b.com,可能未跨域. [要试试,感觉还是不行~]
iframe请求->转发器(b.com)        不跨域,转发器用web服务器(如:nginx,tomcat)
转发器(b.com)->服务器(a.com)  跨域,服务器主动同意跨域.Access-Control-Allow-Origin: *

**Comment by liuqinggang** [comment]
写了下测试，试试可以不,解决单图和涂鸦的上传问题。
多图的使用swf，修改crossdomain即可。
看到用document.domain每个项目都要设置,项目多了需要挨个改。
想用redirect方式试试。
方式：客户端B 提交上传到服务A,A把结果redirect到B的一个页面下（此页面再把数据返回）

上传服务器测试地址http://123.56.40.170:8080,
测试需要把一个文件（redirect.jsp）复制你的项目根目录下。
redirect.jsp 文件:
`<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ page trimDirectiveWhitespaces="true" %>
<%
	request.setCharacterEncoding("utf-8");
	response.setHeader("Content-Type", "text/html");
	response.addHeader("Access-Control-Allow-Origin", "*");
	String s = request.getParameter("s");
	s=java.net.URLDecoder.decode(s,"UTF-8");
	out.write( s);
%>`

测试上传文件（需要修改fromdomain地址为自己的地址）：
`<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <title>ueditor client demo</title>
</head>
<body>

<script id="container" name="content" type="text/plain">
        跨域测试
</script>
<script type="text/javascript" src="/utf8-jsp/ueditor.config.js"></script>
<script type="text/javascript" src="/utf8-jsp/ueditor.all.js"></script>
<script type="text/javascript">
  var ueditorserver="http://123.56.40.170:8080";//我的上传服务器地址
  //你自己的项目地址（来源Referer中有时取不到临时传入）
**  var fromdomain="http://192.168.110.24:8080";**
  var ue = UE.getEditor('container', {
   serverUrl: ueditorserver+"/controller.jsp?fromdomain="+fromdomain
  });
</script>
</body>
</html>
`

**Comment by jeremylzy** [comment]
@tomener 我也遇到单图文上传   iframe跨域问题，请问最后解决了吗

**Comment by baiyunchen** [comment]
现在单页应用越来越火了，我觉得是否可以提供一个配置项，在单图的时候，也使用WebUploader来进行图片的上传，而不采用Iframe，或者单独来一个高版本浏览器的版本，逐步抛弃低版本浏览器。

**Comment by taozhiw** [comment]
### 现代浏览器解决跨域单图上传的方法
思路：
1.  现在的 ueditor 其实单图上传是能上传成功，只是从另外的域名传回的数据放在了一个 iframe 里，导致当前域不能操作 iframe 的数据；
2.  既然如此，如果只需要在现代浏览器中使用，我们完全可以使用 AjAX 代替表单提交，不需要 iframe ，上传收到结果后的处理流程基本和原来的一致了；
3.  剩下的跨域问题就是一般的 AJAX 的跨域问题了。

测试环境：
- UEditor 1.4.3.3 PHP 版；
- Chrome 52;

下面是我修改之后的 initUploadBtn 方法，在代码里为了简单我使用是 fetch 来提交表单的，如果有需要可以换成 XHR 的，跨域亲测有效，由于我们的产品只需要兼容 Chrome ，就没多做测试了，不知道还有没有什么副作用，待观察：
```javascript
function initUploadBtn(){
        var w = containerBtn.offsetWidth || 20,
            h = containerBtn.offsetHeight || 20,
            btnIframe = document.createElement('iframe'),
            btnStyle = 'display:block;width:' + w + 'px;height:' + h + 'px;overflow:hidden;border:0;margin:0;padding:0;position:absolute;top:0;left:0;filter:alpha(opacity=0);-moz-opacity:0;-khtml-opacity: 0;opacity: 0;cursor:pointer;';

        domUtils.on(btnIframe, 'load', function(){

            var timestrap = (+new Date()).toString(36),
                wrapper,
                btnIframeDoc,
                btnIframeBody;

            btnIframeDoc = (btnIframe.contentDocument || btnIframe.contentWindow.document);
            btnIframeBody = btnIframeDoc.body;
            wrapper = btnIframeDoc.createElement('div');

            wrapper.innerHTML = '<form id="edui_form_' + timestrap + '" target="edui_iframe_' + timestrap + '" method="POST" enctype="multipart/form-data" action="' + me.getOpt('serverUrl') + '" ' +
            'style="' + btnStyle + '">' +
            '<input id="edui_input_' + timestrap + '" type="file" accept="image/*" name="' + me.options.imageFieldName + '" ' +
            'style="' + btnStyle + '">' +
            '</form>';

            wrapper.className = 'edui-' + me.options.theme;
            wrapper.id = me.ui.id + '_iframeupload';

            btnIframeBody.style.cssText = btnStyle;
            btnIframeBody.style.width = w + 'px';
            btnIframeBody.style.height = h + 'px';
            btnIframeBody.appendChild(wrapper);

            if (btnIframeBody.parentNode) {
                btnIframeBody.parentNode.style.width = w + 'px';
                btnIframeBody.parentNode.style.height = w + 'px';
            }

            var form = btnIframeDoc.getElementById('edui_form_' + timestrap);
            var input = btnIframeDoc.getElementById('edui_input_' + timestrap);

            domUtils.on(input, 'change', function(){
                if(!input.value) return;
                var loadingId = 'loading_' + (+new Date()).toString(36);
                var params = utils.serializeParam(me.queryCommandValue('serverparam')) || '';

                var imageActionUrl = me.getActionUrl(me.getOpt('imageActionName'));
                var allowFiles = me.getOpt('imageAllowFiles');

                me.focus();
                me.execCommand('inserthtml', '<img class="loadingclass" id="' + loadingId + '" src="' + me.options.themePath + me.options.theme +'/images/spacer.gif" title="' + (me.getLang('simpleupload.loading') || '') + '" >');

                function callback(json){
                    try{
                        var link, loader;
                        link = me.options.imageUrlPrefix + json.url;
                        if(json.state == 'SUCCESS' && json.url) {
                            loader = me.document.getElementById(loadingId);
                            loader.setAttribute('src', link);
                            loader.setAttribute('_src', link);
                            loader.setAttribute('title', json.title || '');
                            loader.setAttribute('alt', json.original || '');
                            loader.removeAttribute('id');
                            domUtils.removeClasses(loader, 'loadingclass');
                        } else {
                            showErrorLoader && showErrorLoader(json.state);
                        }
                    }catch(er){
                        showErrorLoader && showErrorLoader(me.getLang('simpleupload.loadError'));
                    }
                    form.reset();
                }
                function showErrorLoader(title){
                    if(loadingId) {
                        var loader = me.document.getElementById(loadingId);
                        loader && domUtils.remove(loader);
                        me.fireEvent('showmessage', {
                            'id': loadingId,
                            'content': title,
                            'type': 'error',
                            'timeout': 4000
                        });
                    }
                }

                /* 判断后端配置是否没有加载成功 */
                if (!me.getOpt('imageActionName')) {
                    errorHandler(me.getLang('autoupload.errorLoadConfig'));
                    return;
                }
                // 判断文件格式是否错误
                var filename = input.value,
                    fileext = filename ? filename.substr(filename.lastIndexOf('.')):'';
                if (!fileext || (allowFiles && (allowFiles.join('') + '.').indexOf(fileext.toLowerCase() + '.') == -1)) {
                    showErrorLoader(me.getLang('simpleupload.exceedTypeError'));
                    return;
                }
                var uploadUrl = utils.formatUrl(imageActionUrl + (imageActionUrl.indexOf('?') == -1 ? '?':'&') + params);

                // 上传文件
                fetch(uploadUrl, {
                    method: "POST",
                    body: new FormData(form)
                }).then(function(response){
                    return response.json();
                }).then(function(data){
                    callback(data);
                });
            });

            var stateTimer;
            me.addListener('selectionchange', function () {
                clearTimeout(stateTimer);
                stateTimer = setTimeout(function() {
                    var state = me.queryCommandState('simpleupload');
                    if (state == -1) {
                        input.disabled = 'disabled';
                    } else {
                        input.disabled = false;
                    }
                }, 400);
            });
            isLoaded = true;
        });
````

**Comment by DoubleYing** [comment]
有没有php版本的跨域上传图片的例子？求一份~ 810154358@qq.com

**Comment by Aoqin** [comment]
单页面Iframe 跨域很蛋疼啊，能不能修改下，用上面的大大 @taozhiw 重写 initUploadBtn的方法解决了，谢谢

**Comment by baiyunchen** [comment]
感觉Fex团队已经不怎么维护这个编辑器了，我已经转投wangEditor的怀抱了，UEditor已经跟不上现在前端发展的步伐了~

**Comment by reyhappen** [comment]
`document.domain = '父域';`  // 比如www.a.com和image.a.com的父域是a.com，然后iframe就可以获取控制父页面了
