### ISSUE TITLE
UEditor的截图插件UEditorSnapscreen.exe在上传截图时，多出无用参数upload，导致上传失败！

### ISSUE THREAD

**Issue by laihanghui** [fex-team/ueditor#2667]
问题：**UEditor的截图插件UEditorSnapscreen.exe在上传截图时，多出以下无效参数，导致上产失败**：
`
Content-Disposition: form-data; name="upload"
-----------------------------7b4a6d158c9--
`

Java 的Commons-fileupload进行解析时报出如下错误：
`
org.apache.commons.fileupload.MultipartStream$MalformedStreamException: Stream ended unexpectedly
	at org.apache.commons.fileupload.MultipartStream.readHeaders(MultipartStream.java:539)
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.findNextItem(FileUploadBase.java:976)
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.hasNext(FileUploadBase.java:1040)
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:356)
	at org.apache.struts2.dispatcher.multipart.JakartaMultiPartRequest.parse(JakartaMultiPartRequest.java:93)
	at org.apache.struts2.dispatcher.multipart.MultiPartRequestWrapper.<init>(MultiPartRequestWrapper.java:75)
	at org.apache.struts2.dispatcher.Dispatcher.wrapRequest(Dispatcher.java:663)
	at org.apache.struts2.dispatcher.ng.PrepareOperations.wrapRequest(PrepareOperations.java:128)
	at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at cn.zyzz.baseframe.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
`

求发布修复该问题的版本UEditorSnapscreen.exe。

目前的临时**_解决方案_**如下：
重写类org.apache.commons.fileupload.FileUploadBase的方法public List parseRequest(RequestContext ctx)  throws FileUploadException
`
    public List /* FileItem */ parseRequest(RequestContext ctx)
            throws FileUploadException {
        try {
            FileItemIterator iter = getItemIterator(ctx);
            List items = new ArrayList();
            FileItemFactory fac = getFileItemFactory();
            if (fac == null) {
                throw new NullPointerException(
                    "No FileItemFactory has been set.");
            }
            try {
	            while (iter.hasNext()) {
	                FileItemStream item = iter.next();
	                FileItem fileItem = fac.createItem(item.getFieldName(),
	                        item.getContentType(), item.isFormField(),
	                        item.getName());
	                try {
	                    Streams.copy(item.openStream(), fileItem.getOutputStream(),
	                            true);
	                } catch (FileUploadIOException e) {
	                    throw (FileUploadException) e.getCause();
	                } catch (IOException e) {
	                    throw new IOFileUploadException(
	                            "Processing of " + MULTIPART_FORM_DATA
	                            + " request failed. " + e.getMessage(), e);
	                }
	                if (fileItem instanceof FileItemHeadersSupport) {
	                    final FileItemHeaders fih = item.getHeaders();
	                    ((FileItemHeadersSupport) fileItem).setHeaders(fih);
	                }
	                items.add(fileItem);
	            }
            }catch (IOException e) {
            	if(!(e instanceof MalformedStreamException && "Stream ended unexpectedly".equals(e.getMessage()))){
            		throw e;
            	}
            }
            return items;
        } catch (FileUploadIOException e) {
            throw (FileUploadException) e.getCause();
        } catch (IOException e) {
            throw new FileUploadException(e.getMessage(), e);
        }
    }
`

**Comment by Phinome** [comment]
不要用那个截图工具了，后续下掉，推荐使用 IM （如QQ）截图
