### ISSUE TITLE
maven配置上传图片出错 An error occurred at line: 12 in the jsp file: /static/plugins/ueditor/jsp/controller.jsp

### ISSUE THREAD

**Issue by liuhuan543539666** [fex-team/ueditor#2998]
An error occurred at line: [14] in the generated java file: [E:\work\workspace\common-insurance.metadata.plugins\org.eclipse.wst.server.core\tmp0\work\Catalina\localhost\admin\org\apache\jsp\static_\plugins\ueditor\jsp\controller_jsp.java]
Only a type can be imported. com.baidu.ueditor.ActionEnter resolves to a package

An error occurred at line: 12 in the jsp file: /static/plugins/ueditor/jsp/controller.jsp
ActionEnter cannot be resolved to a type
9:  
10:     String rootPath = application.getRealPath( "/" );
11:  
12:     out.write( new ActionEnter( request, rootPath ).exec() );
13:  
14: %>

Stacktrace:] with root cause
org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [14] in the generated java file: [E:\work\workspace\common-insurance.metadata.plugins\org.eclipse.wst.server.core\tmp0\work\Catalina\localhost\admin\org\apache\jsp\static_\plugins\ueditor\jsp\controller_jsp.java]
Only a type can be imported. com.baidu.ueditor.ActionEnter resolves to a package

An error occurred at line: 12 in the jsp file: /static/plugins/ueditor/jsp/controller.jsp
ActionEnter cannot be resolved to a type
9:  
10:     String rootPath = application.getRealPath( "/" );
11:  
12:     out.write( new ActionEnter( request, rootPath ).exec() );
13:  
14: %>

Stacktrace:
    at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103)
    at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:366)
    at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:490)
    at org.apache.jasper.compiler.Compiler.compile(Compiler.java:379)
    at org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
    at org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
    at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:662)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:364)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)

**Comment by qq125800895** [comment]
问下 解决了吗？
