### ISSUE TITLE
Weblogic下无法获取的rootpath

### ISSUE THREAD

**Issue by rosterme** [fex-team/ueditor#3112]
版本：1.4.3.3 JSP 版
环境：weblogic12c+linux  war部署
经过调试验证后，发现目前Ueditor是不支持这样部署，问题的原因在于
controller.jsp 中，这样写法，路径获取是null的。
String rootPath = application.getRealPath( "/" );
修改为获取class 路径，问题解决。（ 详细代码可以百度）
最后还有个关键，weblogic的部署，是要做前后台映射的。在weblogic.xml 增加虚拟地址映射
问题解决，关闭
（最后，最后强烈建议，源码能输出日志（log4j），找问题太痛苦了。）

**Comment by rosterme** [comment]
刚刚用谷歌调试对比一下，发现本机和服务器获取配置文件时有差异
本机：
var imageActionUrl = me.getActionUrl(me.getOpt('imageActionName'));
值："http://localhost:8080/metadata-webapp/resources/lib/ueditor/jsp/controller.jsp?action=uploadimage"
 var allowFiles = me.getOpt('imageAllowFiles');
值：allowFiles = [".png", ".jpg", ".jpeg", ".gif", ".bmp"]
服务器：
var imageActionUrl = me.getActionUrl(me.getOpt('imageActionName'));
值："http://localhost:8080/metadata-webapp/resources/lib/ueditor/jsp/controller.jsp?action="
var allowFiles = me.getOpt('imageAllowFiles');
值：allowFiles =undefined;

**Comment by rosterme** [comment]
今天给源码中增加了些注释，发现初始化不了配置文件，路径获取不了！
`******************ActionEnter Start*************
RootPath:null
******************New ConfigManager() Start*************
RootPath:null
contextPath:null
uri:null
************Ueditor Exception Message**************
java.lang.NullPointerException
        at com.baidu.ueditor.ConfigManager.<init>(ConfigManager.java:44)
        at com.baidu.ueditor.ConfigManager.getInstance(ConfigManager.java:69)
        at com.baidu.ueditor.ActionEnter.<init>(ActionEnter.java:33)
        at jsp_servlet._resources._lib._ueditor._jsp.__controller._jspService(__controller.java:83)
        at weblogic.servlet.jsp.JspBase.service(JspBase.java:35)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)
        at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)
        at weblogic.servlet.internal.ServletStubImpl.onAddToMapException(ServletStubImpl.java:483)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:372)
        at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
        at com.ffcs.crmd.devops.pub.control.TenantFilter.doFilter(TenantFilter.java:86)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
        at com.ffcs.crmd.devops.pub.control.AuthFilter.doFilter(AuthFilter.java:52)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
        at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
        at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:27)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3436)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3402)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
        at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
        at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
        at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2285)
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2201)
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2179)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1572)
        at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:255)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)
******************ActionEnter end*************`

**Comment by Phinome** [comment]
建议虽好，但UEditor 提供的后台程序只是为了快速部署，参考之用，有需求需要自行扩展或者干脆改造。
